language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rcmendes80/docker-react -f Dockefile.dev .

script:
    - docker run -e CI=true rcmendes80/docker-react npm run test