version: '3'
services: 
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - ./src:/app/src
            - ./public:/app/public
    tests:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./src:/app/src
            - ./public:/app/public
        command: npm run test